//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e621_ReBot_v3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("e621_ReBot_v3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _2560SantaHat {
            get {
                object obj = ResourceManager.GetObject("_2560SantaHat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Banner_Tail {
            get {
                object obj = ResourceManager.GetObject("Banner_Tail", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BrowserIcon_Baraag {
            get {
                object obj = ResourceManager.GetObject("BrowserIcon_Baraag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BrowserIcon_e621 {
            get {
                object obj = ResourceManager.GetObject("BrowserIcon_e621", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BrowserIcon_FurAffinity {
            get {
                object obj = ResourceManager.GetObject("BrowserIcon_FurAffinity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BrowserIcon_HentaiFoundry {
            get {
                object obj = ResourceManager.GetObject("BrowserIcon_HentaiFoundry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BrowserIcon_HicceArs {
            get {
                object obj = ResourceManager.GetObject("BrowserIcon_HicceArs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BrowserIcon_Inkbunny {
            get {
                object obj = ResourceManager.GetObject("BrowserIcon_Inkbunny", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BrowserIcon_Mastodon {
            get {
                object obj = ResourceManager.GetObject("BrowserIcon_Mastodon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BrowserIcon_Newgrounds {
            get {
                object obj = ResourceManager.GetObject("BrowserIcon_Newgrounds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BrowserIcon_Pawoo {
            get {
                object obj = ResourceManager.GetObject("BrowserIcon_Pawoo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BrowserIcon_Pixiv {
            get {
                object obj = ResourceManager.GetObject("BrowserIcon_Pixiv", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BrowserIcon_Plurk {
            get {
                object obj = ResourceManager.GetObject("BrowserIcon_Plurk", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BrowserIcon_SoFurry {
            get {
                object obj = ResourceManager.GetObject("BrowserIcon_SoFurry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BrowserIcon_Twitter {
            get {
                object obj = ResourceManager.GetObject("BrowserIcon_Twitter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BrowserIcon_Weasyl {
            get {
                object obj = ResourceManager.GetObject("BrowserIcon_Weasyl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Button_Close {
            get {
                object obj = ResourceManager.GetObject("Button_Close", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Button_Minimize {
            get {
                object obj = ResourceManager.GetObject("Button_Minimize", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CefSharp_Wpf {
            get {
                object obj = ResourceManager.GetObject("CefSharp.Wpf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DiscordLogo {
            get {
                object obj = ResourceManager.GetObject("DiscordLogo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0eff0rt✄0eff0rt_(artist)✄1delkon✄1delkon_(artist)✄1ksrw✄1ksrw_(artist)✄1oi✄1oi_(artist)✄2001maxx✄2001maxx_(artist)✄2dredders✄2dredders_(artist)✄2dreddersart✄2dreddersart_(artist)✄2gecs✄2gecs_(artist)✄2gecsart✄2gecsart_(artist)✄413k✄413k_(artist)✄413k_zzzz✄413k_zzzz_(artist)✄4dbadbooks✄4dbadbooks_(artist)✄69beas✄69beas_(artist)✄7mii✄7mii_(artist)✄abananaman✄abananaman_(artist)✄ablimpfox✄ablimpfox_(artist)✄abobarseem✄abobarseem_(artist)✄abritishfox✄abritishfox_(artist)✄abyssalwolfy✄abyssalwolfy_(artist)✄accel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DNPs {
            get {
                return ResourceManager.GetString("DNPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] E6Image_Deleted {
            get {
                object obj = ResourceManager.GetObject("E6Image_Deleted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] E6Image_Flash {
            get {
                object obj = ResourceManager.GetObject("E6Image_Flash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] E6Image_Loading {
            get {
                object obj = ResourceManager.GetObject("E6Image_Loading", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FolderIcon {
            get {
                object obj = ResourceManager.GetObject("FolderIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?/?✄?/am✄?/c✄?/cuntboy✄?/d✄?/dickgirl✄?/f✄?/female✄?/gm✄?/h✄?/herm✄?/i✄?/intersex✄?/m✄?/male✄?/p/f✄?/p/m✄♀_penetrating_♀✄♀_penetrating_♂✄♂_penetrating_♀✄♂_penetrating_♂✄1_boy✄1_futa✄1_futanari✄1_girl✄1_guys✄1_intersex✄1boy✄1futa✄1futanari✄1girl✄1girls✄1guy✄1intersex✄1male✄2_boys✄2_girl✄2_girls✄2_guys✄2boys✄2girl✄2girls✄2guys✄3_boys✄3_girl✄3_girls✄3_guys✄3boys✄3girl✄3girls✄3guys✄4_boys✄4_girl✄4_girls✄4_guys✄4boys✄4girl✄4girls✄4guys✄5_girls✄5boys✄5guys✄7girls✄a/a✄a/d✄a/f✄a/h✄a/i✄a/m✄adult_ambiguous✄adult_andr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string genders {
            get {
                return ResourceManager.GetString("genders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GitHubLogo {
            get {
                object obj = ResourceManager.GetObject("GitHubLogo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HtmlAgilityPack {
            get {
                object obj = ResourceManager.GetObject("HtmlAgilityPack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Http_Formatting {
            get {
                object obj = ResourceManager.GetObject("Http_Formatting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Icon_Flag {
            get {
                object obj = ResourceManager.GetObject("Icon_Flag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Icon_Note {
            get {
                object obj = ResourceManager.GetObject("Icon_Note", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Icon_Upload {
            get {
                object obj = ResourceManager.GetObject("Icon_Upload", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ko_Fi_Button {
            get {
                object obj = ResourceManager.GetObject("Ko_Fi_Button", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ko_Fi_ButtonSmall {
            get {
                object obj = ResourceManager.GetObject("Ko_Fi_ButtonSmall", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MenuIcon_Browser {
            get {
                object obj = ResourceManager.GetObject("MenuIcon_Browser", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MenuIcon_Downloads {
            get {
                object obj = ResourceManager.GetObject("MenuIcon_Downloads", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MenuIcon_Grid {
            get {
                object obj = ResourceManager.GetObject("MenuIcon_Grid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MenuIcon_Information {
            get {
                object obj = ResourceManager.GetObject("MenuIcon_Information", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MenuIcon_Jobs {
            get {
                object obj = ResourceManager.GetObject("MenuIcon_Jobs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MenuIcon_Logs {
            get {
                object obj = ResourceManager.GetObject("MenuIcon_Logs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MenuIcon_Settings {
            get {
                object obj = ResourceManager.GetObject("MenuIcon_Settings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MenuIcon_Welcome {
            get {
                object obj = ResourceManager.GetObject("MenuIcon_Welcome", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Newtonsoft_Json {
            get {
                object obj = ResourceManager.GetObject("Newtonsoft_Json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReBot_Icon {
            get {
                object obj = ResourceManager.GetObject("ReBot_Icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ReBot_Logo {
            get {
                object obj = ResourceManager.GetObject("ReBot_Logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
